#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";
use Cal::DAV::Sync::App;

use Data::Dump qw/dump/;

my $app = Cal::DAV::Sync::App->new_with_options();

# $app->run;

# print $app->get_calendar_home('https://ms1.startsiden.no/principals/users/bolav/'),"\n";
# exit(0);

dump $app->get_calendars('https://ms1.startsiden.no/dav/bolav/');
exit(0);

my $res;
my $res3 = $app->cal->dav->new_resource( -uri => 'https://www.google.com/calendar/dav/bolavs@gmail.com/events/');
$res3->propfind( -depth => 1, -text => '
<D:prop>
 <CS:getctag xmlns:CS="http://calendarserver.org/ns/"/>
 <D:displayname/>
 <x2:calendar-description xmlns:x2="urn:ietf:params:xml:ns:caldav"/>
 <x3:calendar-color xmlns:x3="http://apple.com/ns/ical/"/>
 <x3:calendar-order xmlns:x3="http://apple.com/ns/ical/"/>
 <D:resourcetype/>
 <x2:calendar-free-busy-set xmlns:x2="urn:ietf:params:xml:ns:caldav"/>
</D:prop>
' );


# exit(0);

use HTTP::Headers;
my $depth;

   # 'depth' default is 1
   $depth = 1 unless ( defined $depth && $depth ne "" );
    
   ####
   # Setup the headers for the request
   my $headers = new HTTP::Headers;
   $headers->header("Content-type", "text/xml; charset=\"utf-8\"");
   $headers->header("Depth", $depth);

   # Create a new XML document
   #   <D:propfind xmlns:D="DAV:">
   #       <D:allprop/>
   #   </D:propfind>

=for
   my $xml_request = qq{<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:x2="http://calendarserver.org/ns/" xmlns:x1="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV:">
 <D:prop>
  <x1:calendar-home-set xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
  <x1:calendar-user-address-set xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
  <x1:schedule-inbox-URL xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
  <x1:schedule-outbox-URL xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
  <D:displayname/>
 </D:prop>
</D:propfind>
};
=cut
   my $xml_request = qq{<?xml version="1.0" encoding="utf-8"?>
   <x0:propfind xmlns:x1="http://calendarserver.org/ns/" xmlns:x0="DAV:" xmlns:x3="http://apple.com/ns/ical/" xmlns:x2="urn:ietf:params:xml:ns:caldav">
    <x0:prop>
     <x1:getctag/>
     <x0:displayname/>
     <x2:calendar-description/>
     <x3:calendar-color/>
     <x3:calendar-order/>
     <x0:resourcetype/>
     <x2:calendar-free-busy-set/>
    </x0:prop>
   </x0:propfind>
};


   ####
   # Put the propfind request to the remote server
   my $resp= $res->{_comms}->do_http_request (
          -method  => "PROPFIND",
          -url     => 'https://www.google.com/calendar/dav/bolavs@gmail.com/user/',
          -headers => $headers,
          -content => $xml_request,
      );


   if ( $resp->content_type !~ m#text/xml# ) {
      $resp->add_status_line("HTTP/1.1 422 Unprocessable Entity, no XML body.",
                             "", $res->{_uri}, $res->{_uri});
   } else {

      # use XML::DOM to parse the result.
      my $parser = new XML::DOM::Parser;
      my $doc = $parser->parse($resp->content);

      # Setup a ResourceList in which to pump all of the collection 
      my $resource_list;
      eval { $resource_list = $res->_XML_parse_multistatus( $doc, $resp ) };

      warn "XML error: " . $@ if $@;

      if ($resource_list && $resource_list->count_resources() ) {
         $res->{_resource_list} = $resource_list;
      } else {
         $res->{_resource_list} = undef;
      }

      $doc->dispose;
   }


