#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";
use Cal::DAV::Sync::App;

use Data::Dump qw/dump/;

my $app = Cal::DAV::Sync::App->new_with_options();

$app->run;

# dump $app->get_calendar_home('https://www.google.com/calendar/dav/bolavs@gmail.com/user/');
# dump $app->get_calendars('https://www.google.com/calendar/dav/bolavs@gmail.com/')