#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Cal::DAV::Sync::Schema;

my $dsn = 'dbi:SQLite:sync.db';

$dsn = $ARGV[0] if ($ARGV[0]);

print "Connecting to $dsn\n";

my $schema = Cal::DAV::Sync::Schema->connect($dsn);
$schema->deploy;
